# Generated by Django 4.2.1 on 2023-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_item_url_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
